on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yaml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: 13 0 * * *

name: Semgrep Lockfileless Scanning

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-22.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install System Dependencies (Java & Maven)
        run: |
          apk add --no-cache openjdk17 maven
      - name: Run Semgrep CI with Lockfileless Scanning
        run: |
          semgrep ci --allow-local-builds --supply-chain